import * as React from "react";
import type { FileReadPreview } from "../types";

type Props = {
  filePreview: FileReadPreview;
  operation: import("../types").WebviewState["coding"]["documentOperation"];
  busyAction: import("../types").WebviewState["coding"]["busyAction"];
  onInspect: () => void;
  onExtract: () => void;
  onPlanExport: (exportFormat: "markdown" | "text") => void;
  onApplyExport: () => void;
  onPlanEdit: (operation: string, parameters: Record<string, unknown>) => void;
  onApplyEdit: () => void;
};

function asRecord(value: unknown): Record<string, unknown> {
  return typeof value === "object" && value !== null ? value as Record<string, unknown> : {};
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function defaultEditFor(filePreview: FileReadPreview): { operation: string; parameters: Record<string, unknown>; label: string; reason?: string } {
  const operations = filePreview.descriptor?.stable_edit_operations ?? [];
  const relative = filePreview.relative_path ?? filePreview.file_label;
  if (operations.includes("append_paragraph")) {
    return { operation: "append_paragraph", parameters: { text: "Approved Codev document note." }, label: "Plan DOCX append paragraph" };
  }
  if (operations.includes("set_cell")) {
    return { operation: "set_cell", parameters: { sheet: "Data", cell: "A1", value: "Approved Codev value" }, label: "Plan XLSX set cell" };
  }
  if (operations.includes("append_slide")) {
    return { operation: "append_slide", parameters: { title: "Approved Codev Slide", body: "Generated by approved local document edit." }, label: "Plan PPTX append slide" };
  }
  return { operation: "unsupported", parameters: {}, label: "Plan stable edit", reason: `${relative} has no stable edit operation exposed for this format.` };
}

export default function DocumentPreviewPanel({ filePreview, operation, busyAction, onInspect, onExtract, onPlanExport, onApplyExport, onPlanEdit, onApplyEdit }: Props) {
  const summary = asRecord(filePreview.parse_summary);
  const metadata = asRecord(summary.metadata);
  const safety = asRecord(summary.safety);
  const warnings = asArray(summary.warnings).map(String);
  const redactions = asArray(summary.redactions).map(String);
  const editable = Boolean(filePreview.descriptor?.editable);
  const exportable = filePreview.descriptor?.exportable !== false;
  const edit = defaultEditFor(filePreview);
  const exportReady = operation?.exportPlan?.status === "planned";
  const editReady = operation?.editPlan?.status === "planned";

  return (
    <div className="document-preview">
      <div className="document-preview__head">
        <div>
          <strong>{String(summary.document_label ?? filePreview.file_type_label ?? "Document")}</strong>
          <p className="muted">
            {String(summary.document_family ?? "document")} · adapter {String(summary.adapter ?? filePreview.adapter ?? "document")} · status {String(summary.status ?? filePreview.status)}
          </p>
        </div>
        <span className={safety.allowed === false ? "pill pill--warn" : "pill"}>
          {safety.allowed === false ? "blocked" : "safe preview"}
        </span>
      </div>
      <dl className="facts facts--single">
        <div><dt>Byte hash</dt><dd>{String(safety.byte_hash ?? filePreview.byte_hash ?? "not returned")}</dd></div>
        <div><dt>Size</dt><dd>{String(safety.size_bytes ?? filePreview.byte_count ?? 0)} bytes</dd></div>
        <div><dt>Outline</dt><dd>{String(summary.outline_count ?? 0)} items</dd></div>
        <div><dt>Tables</dt><dd>{String(summary.table_count ?? 0)} previews</dd></div>
        <div><dt>Provenance</dt><dd>{String(summary.provenance_count ?? 0)} references</dd></div>
      </dl>
      {Object.keys(metadata).length ? (
        <div className="document-preview__meta">
          <strong>Metadata</strong>
          <dl className="facts facts--single">
            {Object.entries(metadata).slice(0, 12).map(([key, value]) => (
              <div key={key}><dt>{key}</dt><dd>{Array.isArray(value) ? value.join(", ") : String(value ?? "not set")}</dd></div>
            ))}
          </dl>
        </div>
      ) : null}
      {warnings.length ? <p className="muted">Document warnings: {warnings.join(" ")}</p> : null}
      {redactions.length ? <p className="muted">Redactions: {redactions.join(" ")}</p> : null}
      <div className="button-row">
        <button className="ghost" disabled={busyAction === "documentInspect"} onClick={onInspect}>
          {busyAction === "documentInspect" ? "Inspecting..." : "Inspect document"}
        </button>
        <button className="ghost" disabled={busyAction === "documentExtract"} onClick={onExtract}>
          {busyAction === "documentExtract" ? "Extracting..." : "Extract preview"}
        </button>
        <button className="ghost" disabled={!exportable || busyAction === "documentExportPlan"} onClick={() => onPlanExport("markdown")}>
          Plan Markdown export
        </button>
        <button className="ghost" disabled={!exportable || busyAction === "documentExportPlan"} onClick={() => onPlanExport("text")}>
          Plan text export
        </button>
        <button className="ghost" disabled={!exportReady || busyAction === "documentExportApply"} onClick={onApplyExport}>
          Approve export
        </button>
        <button className="ghost" disabled={!editable || Boolean(edit.reason) || busyAction === "documentEditPlan"} onClick={() => onPlanEdit(edit.operation, edit.parameters)}>
          {edit.label}
        </button>
        <button className="ghost" disabled={!editReady || busyAction === "documentEditApply"} onClick={onApplyEdit}>
          Approve stable edit
        </button>
      </div>
      {!exportable ? <p className="muted">Export is not supported for this document type.</p> : null}
      {edit.reason ? <p className="muted">{edit.reason}</p> : null}
      {operation?.exportPlan ? (
        <div className="document-preview__result">
          <strong>Export plan</strong>
          <p className="muted">{operation.exportPlan.status}: {operation.exportPlan.plan_summary}</p>
          {operation.exportPlan.blocked_reason ? <p className="error-note">Blocked: {operation.exportPlan.blocked_reason}</p> : null}
          {operation.exportPlan.preview ? <pre className="source-preview source-preview--compact">{operation.exportPlan.preview}</pre> : null}
        </div>
      ) : null}
      {operation?.editPlan ? (
        <div className="document-preview__result">
          <strong>Edit plan</strong>
          <p className="muted">{operation.editPlan.status}: {operation.editPlan.plan_summary}</p>
          {operation.editPlan.blocked_reason ? <p className="error-note">Blocked: {operation.editPlan.blocked_reason}</p> : null}
          {operation.editPlan.preview ? <pre className="source-preview source-preview--compact">{operation.editPlan.preview}</pre> : null}
        </div>
      ) : null}
      {operation?.applyResult ? (
        <div className="document-preview__result">
          <strong>Operation result</strong>
          <p className="muted">
            {operation.applyResult.action} {operation.applyResult.status} · mutation {operation.applyResult.mutation_performed ? "yes" : "no"} · audit {operation.applyResult.audit_written ? "yes" : "no"}
          </p>
          {operation.applyResult.blocked_reason ? <p className="error-note">Blocked: {operation.applyResult.blocked_reason}</p> : null}
          <p className="muted">{operation.applyResult.rollback_note}</p>
        </div>
      ) : null}
      {operation?.lastError ? <p className="error-note">{operation.lastError}</p> : null}
      <p className="muted">
        Macros, formulas, embedded scripts, external links, media, and document automation are not executed. Exports and stable edits remain approval-gated through Elysia core.
      </p>
    </div>
  );
}
