export type ApprovalMode = "read_only" | "plan_only" | "path_preview" | "apply_with_approval" | "test_with_approval";
export type ConnectionState = "unknown" | "connected" | "unavailable";
export type WorkMode = "local" | "developer_forge";

export type UiSession = {
  id: string;
  backendSessionId?: string;
  title: string;
  workspaceLabel: string;
  createdAt: string;
  updatedAt: string;
  status: string;
  approvalMode: ApprovalMode;
};

export type CodingBoundaryFlags = {
  local_only: boolean;
  marketplace_account_required: boolean;
  cloud_upload_allowed: boolean;
  selected_file_read_allowed: boolean;
  patch_proposal_allowed: boolean;
  patch_apply_allowed: boolean;
  command_execution_allowed: boolean;
  test_execution_allowed: boolean;
  git_mutation_allowed: boolean;
  package_manager_allowed: boolean;
  autonomous_loop_allowed: boolean;
  source_contents_included: boolean;
};

export type CodingBridgeStatus = {
  available: boolean;
  contract_version: string;
  local_api_base: string;
  boundaries: CodingBoundaryFlags;
  enabled_endpoints: string[];
  disabled_capabilities: string[];
  notes: string[];
};

export type RepoInspectPreview = {
  workspace_label: string;
  workspace_root_hash: string;
  max_depth: number;
  max_entries: number;
  entries_returned: number;
  ignored_entries: string[];
  preview_entries: Array<{ relative_path: string; kind: string; depth: number }>;
  source_contents_included: boolean;
  files_read: string[];
  boundaries: CodingBoundaryFlags;
};

export type ActiveFileDescriptor = {
  fileName: string;
  relativePath: string;
  languageId: string;
  scheme: string;
  isDirty: boolean;
};

export type FileReadPreview = {
  status: string;
  file_label: string;
  relative_path?: string;
  path_hash: string;
  content_hash?: string;
  byte_hash?: string;
  language_hint?: string;
  file_type_id?: string;
  file_type_label?: string;
  category?: string;
  adapter?: string;
  language_id?: string;
  encoding?: string;
  line_ending?: string;
  line_count?: number;
  byte_count?: number;
  parse_status?: string;
  parse_summary?: Record<string, unknown>;
  risk_flags?: {
    secret_sensitive: boolean;
    generated_sensitive: boolean;
    lockfile: boolean;
    executable_sensitive: boolean;
  };
  capabilities?: {
    readable: boolean;
    writable: boolean;
    patchable: boolean;
    creatable: boolean;
    deletable: boolean;
    renameable: boolean;
  };
  redactions?: string[];
  source_contents_included: boolean;
  content_preview?: string;
  bytes_returned: number;
  lines_returned: number;
  truncated: boolean;
  blocked_reason?: string;
  warnings: string[];
  secret_scan_findings: string[];
  boundaries: CodingBoundaryFlags;
  descriptor?: {
    type_id: string;
    label: string;
    extension?: string;
    extensions?: string[];
    family?: string;
    media_family?: string;
    mime_types?: string[];
    adapter?: string;
    readable?: boolean;
    extractable?: boolean;
    exportable?: boolean;
    editable?: boolean;
    stable_edit_operations?: string[];
    risk_flags?: Record<string, boolean>;
    capabilities?: Record<string, boolean>;
    notes?: string[];
  };
  safety?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  schema_summary?: Record<string, unknown>;
  preview?: Record<string, unknown>;
  layers?: Array<Record<string, unknown>>;
  bands?: Array<Record<string, unknown>>;
  dimensions?: Array<Record<string, unknown>>;
  variables?: Array<Record<string, unknown>>;
  redaction_count?: number;
  preview_truncated?: boolean;
  dependencies?: Record<string, unknown>;
  text_preview?: string;
  tables?: Array<Record<string, unknown>>;
  outline?: Array<Record<string, unknown>>;
  provenance?: Array<Record<string, unknown>>;
  size_bytes?: number;
  media_family?: string;
  container?: string;
  duration_seconds?: number;
  bitrate_bps?: number;
  stream_count?: number;
  audio?: Record<string, unknown>;
  video?: Record<string, unknown>;
  privacy_flags?: Record<string, boolean>;
  safety_flags?: Record<string, boolean>;
  thumbnail_status?: string;
  thumbnail_data_url?: string;
  thumbnail_path?: string;
  operation_id?: string;
  request_id?: string;
  audit_written?: boolean;
};

export type UiMessage = {
  id: string;
  role: "user" | "elysia" | "system";
  text: string;
  createdAt: string;
};

export type WebviewState = {
  connection: { state: ConnectionState; apiUrl: string; summary: string; checkedAt?: string };
  workspace: {
    trustLevel: string;
    workspaceLabel: string;
    workspaceFolders: string[];
    workspaceRoot?: string;
    canReadWorkspace: boolean;
    canProposePatch: boolean;
    canApplyPatch: boolean;
    canRunCommand: boolean;
  };
  activeFile: ActiveFileDescriptor | null;
  sessions: UiSession[];
  activeSessionId: string | null;
  messages: UiMessage[];
  approvalMode: ApprovalMode;
  approvalModeCapabilities: {
    canReadApprovedFile: boolean;
    canInspectPaths: boolean;
    canProposePatch: boolean;
    canApplyPatch: boolean;
    canRunChecks: boolean;
    description: string;
  };
  workMode: {
    mode: WorkMode;
    forgeConnected: boolean;
    forgeStatus: "not_connected" | "placeholder" | "disabled";
    selectedContextSendAllowed: boolean;
    notes: string[];
  };
  ideContext: {
    workspaceMetadata: boolean;
    activeFileMetadata: boolean;
    approvedFilePreview: boolean;
    diagnosticsSummary: boolean;
  };
  goalWorkflow: {
    status: "idle" | "planning" | "preview_only" | "stopped";
    currentGoal?: string;
    autonomyEnabled: false;
    pursueGoalEnabled: false;
    fullOperatorEnabled: false;
    notes: string[];
  };
  git: { branch: string; dirtyState: string; changedCount: number; summary: string };
  changedFiles: Array<{ path: string; state: string }>;
  patchPreview: {
    state: string;
    summary: string;
    files: string[];
    canApply: boolean;
    diffPreview?: string;
    patchHash?: string;
    warnings?: string[];
  };
  coding: {
    bridge: CodingBridgeStatus | null;
    repoPreview: RepoInspectPreview | null;
    filePreview: FileReadPreview | null;
    patchApplyResult: {
      status: string;
      target_relative_path?: string;
      mutation_performed: boolean;
      audit_written: boolean;
      approval_id?: string;
      request_id?: string;
      operation_id?: string;
      backup_relative_path?: string;
      rollback_receipt_id?: string;
      blocked_reason?: string;
      rollback_note: string;
      warnings: string[];
    } | null;
    commandResult: {
      status: string;
      command_id: string;
      execution_performed: boolean;
      exit_code?: number;
      stdout_preview?: string;
      stderr_preview?: string;
      blocked_reason?: string;
      audit_written: boolean;
      approval_id?: string;
      request_id?: string;
      operation_id?: string;
      warnings: string[];
    } | null;
    documentOperation: {
      inspectPreview: FileReadPreview | null;
      extractPreview: FileReadPreview | null;
      exportPlan: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        plan_summary: string;
        source_hash?: string;
        plan_hash?: string;
        preview?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        approval_required: boolean;
      } | null;
      editPlan: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        plan_summary: string;
        source_hash?: string;
        plan_hash?: string;
        preview?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        approval_required: boolean;
      } | null;
      applyResult: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        mutation_performed: boolean;
        audit_written: boolean;
        previous_hash?: string;
        new_hash?: string;
        approval_id?: string;
        request_id?: string;
        operation_id?: string;
        backup_relative_path?: string;
        rollback_receipt_id?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        rollback_note: string;
      } | null;
      lastError?: string;
    } | null;
    dataOperation: {
      inspectPreview: FileReadPreview | null;
      extractPreview: FileReadPreview | null;
      exportPlan: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        plan_summary: string;
        source_hash?: string;
        plan_hash?: string;
        preview?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        transaction?: Record<string, unknown>;
        backup?: Record<string, unknown>;
        approval_required: boolean;
      } | null;
      mutationPlan: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        plan_summary: string;
        source_hash?: string;
        plan_hash?: string;
        preview?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        transaction?: Record<string, unknown>;
        backup?: Record<string, unknown>;
        approval_required: boolean;
      } | null;
      applyResult: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        mutation_performed: boolean;
        audit_written: boolean;
        previous_hash?: string;
        new_hash?: string;
        approval_id?: string;
        request_id?: string;
        operation_id?: string;
        backup_relative_path?: string;
        rollback_receipt_id?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        transaction?: Record<string, unknown>;
        backup?: Record<string, unknown>;
        rollback_note: string;
      } | null;
      lastError?: string;
    } | null;
    visualOperation: {
      inspectPreview: FileReadPreview | null;
      extractPreview: FileReadPreview | null;
      ocrResult: Record<string, unknown> | null;
      analysisResult: Record<string, unknown> | null;
      exportPlan: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        plan_summary: string;
        source_hash?: string;
        plan_hash?: string;
        preview?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        approval_required: boolean;
      } | null;
      editPlan: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        plan_summary: string;
        source_hash?: string;
        plan_hash?: string;
        preview?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        approval_required: boolean;
      } | null;
      applyResult: {
        status: string;
        action: string;
        file_label: string;
        relative_path?: string;
        target_relative_path?: string;
        blocked_reason?: string;
        mutation_performed: boolean;
        audit_written: boolean;
        previous_hash?: string;
        new_hash?: string;
        approval_id?: string;
        request_id?: string;
        operation_id?: string;
        backup_relative_path?: string;
        rollback_receipt_id?: string;
        warnings: string[];
        operation_details?: Record<string, unknown>;
        rollback_note: string;
      } | null;
      lastError?: string;
    } | null;
    mediaOperation: {
      inspectPreview: FileReadPreview | null;
      thumbnailPreview: FileReadPreview | null;
      lastError?: string;
    } | null;
    fileOperation: {
      plan: {
        status: string;
        operation_kind: string;
        target_relative_path?: string;
        destination_relative_path?: string;
        blocked_reason?: string;
        source_hash?: string;
        plan_hash?: string;
        plan_steps: string[];
        risk_labels: string[];
        warnings: string[];
      } | null;
      result: {
        status: string;
        operation_kind: string;
        target_relative_path?: string;
        destination_relative_path?: string;
        previous_content_hash?: string;
        new_content_hash?: string;
        backup_relative_path?: string;
        rollback_receipt_id?: string;
        mutation_performed: boolean;
        audit_written: boolean;
        blocked_reason?: string;
        rollback_note: string;
        warnings: string[];
        request_id?: string;
      } | null;
      lastError?: string;
    } | null;
    operationAudits: Array<{
      timestamp_utc?: string;
      recorded_at_utc?: string;
      kind?: string;
      status?: string;
      request_id?: string;
      session_id?: string;
      operation_id?: string;
      approval_id?: string;
      operation_kind?: string;
      relative_paths?: string[];
      relative_path?: string;
      source_hash?: string;
      plan_hash?: string;
      result_hash?: string;
      mutation_performed?: boolean;
      shell_execution?: boolean;
      backup?: Record<string, unknown>;
      audit_persisted?: boolean;
      media_family?: string;
      size_bytes?: number;
      duration_seconds?: number;
      stream_count?: number;
      thumbnail_status?: string;
      privacy_flags_present?: boolean;
      approval_required?: boolean;
      operator_approved?: boolean;
    }>;
    lastError?: string;
    busyAction?: "refresh" | "newSession" | "chat" | "repoPreview" | "filePreview" | "applyPatch" | "runCheck" | "deleteSession" | "clearSessions" | "fileOperationPlan" | "fileOperationApply" | "documentInspect" | "documentExtract" | "documentExportPlan" | "documentExportApply" | "documentEditPlan" | "documentEditApply" | "dataInspect" | "dataPreview" | "dataExportPlan" | "dataExportApply" | "dataMutationPlan" | "dataMutationApply" | "visualInspect" | "visualPreview" | "visualOcr" | "visualAnalysis" | "visualExportPlan" | "visualExportApply" | "visualEditPlan" | "visualEditApply" | "mediaInspect" | "mediaThumbnail";
    lastAction?: string;
  };
};

export type VsCodeApi = {
  postMessage(message: unknown): void;
  getState(): unknown;
  setState(state: unknown): void;
};
